name: Publish to NuGet

on:
  workflow_run:
    workflows: [ "Build & Test" ]
    types: [ completed ]

concurrency:
  group: nuget-${{ github.ref }}
  cancel-in-progress: false

jobs:
  publish:
    if: github.event.workflow_run.conclusion == 'success'
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Download git reference data
        uses: actions/download-artifact@v4
        with:
          name: push-reference
          path: ${{ github.workspace }}/.
        
      - name: Extract git reference data
        id: git-data
        run: bash "${GITHUB_WORKSPACE}/.github/workflows/scripts/nuget/extract-git-ref-data.sh"
        
      - name: Validate tag format
        run: |
          TAG_NAME="${{ steps.git-data.outputs.GIT_TAG }}"
          if [[ -z "$TAG_NAME" ]]; then
            echo "No tag found. Skipping publish."
            exit 0
          fi
          if [[ ! "$TAG_NAME" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            echo "Tag format invalid: $TAG_NAME. Skipping publish."
            exit 0
          fi
          echo "Valid tag: $TAG_NAME"
      
      - name: Download .NET versions artifact
        uses: actions/download-artifact@v4
        with:
          name: dotnet-versions
          path: ./data/versions
        
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-artifacts
          path: ./data/artifacts
          
      - name: Determine highest .NET version
        id: highest-dotnet
        run: bash "${GITHUB_WORKSPACE}/.github/workflows/scripts/nuget/extract-highest-version.sh"

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ steps.highest-dotnet.outputs.DOTNET_VERSION }}
        env:
          NUGET_AUTH_TOKEN: ${{ secrets.SOFTOMNI_NUGET_KEY }}

      - name: Pack
        run: dotnet pack --configuration Release --output ./artifacts

      - name: Publish
        run: dotnet nuget push ./artifacts/*.nupkg \
          --api-key ${{ secrets.SOFTOMNI_NUGET_KEY }} \
          --source https://api.nuget.org/v3/index.json
