name: Build & Test

on:
  push:
    branches:
      - "*"

jobs:
  generate-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
      highest: ${{ steps.set-matrix.outputs.highest }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate .NET versions matrix and determine highest version
        id: set-matrix
        run: bash "${GITHUB_WORKSPACE}/.github/workflows/scripts/push/set-matrix.sh"

  build:
    needs: generate-matrix
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Determine .NET SDK version for build (highest)
        id: sdk-version-build
        run: bash "${GITHUB_WORKSPACE}/.github/workflows/scripts/push/set-dotnet-version-for-build.sh" ${{ needs.generate-matrix.outputs.highest }}

      - name: Setup .NET for build
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ steps.sdk-version-build.outputs.sdk_version }}

      - name: Set VERSION variable from tag or commit
        run: bash "${GITHUB_WORKSPACE}/.github/workflows/scripts/push/set-version-tag.sh"

      - name: Build solution using highest .NET version
        run: dotnet build --configuration Release /p:Version=${{ env.VERSION }}
        shell: bash

  test:
    needs: [generate-matrix, build]
    runs-on: ubuntu-latest
    # Use the matrix generated in the previous job. If the JSON is empty,
    # this will result in no test jobs being run.
    strategy:
      matrix: ${{ fromJson(needs.generate-matrix.outputs.matrix) }}
      fail-fast: false
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Determine .NET SDK version for testing
        id: sdk-version-test
        run: bash "${GITHUB_WORKSPACE}/.github/workflows/scripts/push/set-dotnet-version-for-tests.sh" "${{ matrix.dotnet_version }}"

      - name: Setup .NET for test
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ steps.sdk-version-test.outputs.sdk_version }}

      - name: Set VERSION variable from tag or commit
        run: bash "${GITHUB_WORKSPACE}/.github/workflows/scripts/push/set-version-tag-for-tests.sh"
        
      - name: Setup directory for tests
        run: bash "${GITHUB_WORKSPACE}/.github/workflows/scripts/push/setup-directory.sh" "${{ matrix.dotnet_version }}" "${GITHUB_WORKSPACE}"

      - name: Run tests for all test projects using target framework "${{ matrix.dotnet_version }}"
        run: bash "${GITHUB_WORKSPACE}/.github/workflows/scripts/push/run-tests.sh" "${{ matrix.dotnet_version }}" "${{ env.VERSION }}"
        
      - name: Debug file tree
        run: tree

      - name: Publish test results artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results-${{ matrix.dotnet_version }}
          path: "test_results/${{ matrix.dotnet_version }}/*.trx"

      - name: Report test results
        if: always()
        uses: dorny/test-reporter@v1
        with:
          name: .NET Tests (${{ matrix.dotnet_version }})
          path: "test_results/${{ matrix.dotnet_version }}/*.trx"
          reporter: dotnet-trx
